### PR TITLE
Create example-with-features.yaml

### PR DESCRIPTION
**Pull request by lordratner**
All features are internal to the unit, no Home Assistant reliance other than to see the readings.

On/Off added - One tap for turning the power switch on, two slow taps for off. Status light changes to indicate success. 

All component names updated to work with new HA entity naming convention

Main and status lights made internal, using logic from sensors to change. 

Alarm actions added. First a flashing red light, then 30 seconds later, a buzzer

Battery low light mode added

Party mode and Night light added. Switches in HA

Goal here was to keep the unit functional even with an internet/network failure, with basic core functionality.. Everything still available for automations within HA

### CODE REVIEW

**Comment by andyboeh** [comment]
Thanks, it's very similar to the one I'm actually using - but I don't need lambdas for it ;)

Yours is for the Sense-U base station, right?

**Comment by lordratner** [comment]
Yeah, I'm using the Base Station 2.

Lambdas are just so much quicker than the ESPHome YAML, and I'm lazy 😂🤣

Looking forward to seeing what you came up with so I can cannibalize it into mine. The only thing I'm not happy with right now is the on/off using the touch sensor. It's super sensitive so double tapping it is not smooth. I think I'm going to change it to a long-press to toggle on and off.

**Comment by andyboeh** [comment]
> I think I'm going to change it to a long-press to toggle on and off.

This is what I use... :)

**Comment by andyboeh** [comment]
I added two more examples that I came up with. I also added the `reboot_timeout: 0s` to your config so that the ESP does not reboot if it doesn't detect a WiFi connection.

**Pull request merged**
